# Generated by Django 5.2.8 on 2025-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTube video havolasi', null=True),
        ),
    ]
